name = "aurashop-marketplace"
main = "src/edge/worker.js"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DEFAULT_CURRENCY = "ETB"
NODE_ENV = "production"
TELEGRAM_BOT_USERNAME = "aurashop_marketplace_bot"
TELEGRAM_CHANNEL_ID = "@Aurashop_marketplace"
ADMIN_TELEGRAM_IDS = "1890482340,7117509984,5356565604,8282129488"
ADMIN_CHAT_ID = "1890482340"
MONGODB_DATABASE = "efootball"
MONGO_URI = "mongodb+srv://ronaldozgoat77_db_user:y8G6YUJGmgBDJaHg@cluster0.1pp7nvf.mongodb.net/efootball?appName=Cluster0"
APP_URL = "https://aurashop-marketplace.<your-subdomain>.workers.dev"

[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "development"

[[kv_namespaces]]
binding = "TELEGRAM_SESSIONS"
id = "83310251a6be499b922be1af7e5f0a07"
preview_id = "83310251a6be499b922be1af7e5f0a07"

[triggers]
crons = ["*/5 * * * *"]

[env.production.triggers]
crons = ["*/5 * * * *"]
